apiVersion: v1
kind: ConfigMap
metadata:
  name: ocp-config
  namespace: ocp 
data:
  eureka.client.serviceUrl.defaultZone: "http://eureka-0.eureka.ocp.svc.cluster.local:1111/eureka,http://eureka-1.eureka.ocp.svc.cluster.local:1111/eureka,http://eureka-2.eureka.ocp.svc.cluster.local:1111/eureka"
  spring.datasource.druid.core.url: "jdbc:mysql://auth-center:3306/oauth-center?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false"
  spring.datasource.druid.log.url: "jdbc:mysql://log-center:3306/oauth-center?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false"
  spring.redis.host: "redis-service"
